services:
  - type: web
    name: foodfactory-backend
    runtime: docker
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?useSSL=true&serverTimezone=UTC
      - key: DB_USER
        value: 3AHxi4bKkwrCqvA.root
      - key: DB_PASSWORD
        value: GxgBEyntx5OqzQ5t
      - key: JAVA_OPTS
        value: "-Xmx512m -XX:+UseContainerSupport -Dspring.profiles.active=prod"
